version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - 5432:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: nestjs
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: nestjs
  test-db:
    image: mysql:5.7
    ports:
      - 5434:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: nestjs
      MYSQL_PASSWORD: 123
      MYSQL_DATABASE: nestjs
    command: ["--default-authentication-plugin=mysql_native_password"]